//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgency.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentDemands
    {
        public int ID_ApartmentDemands { get; set; }
        public string Address_City { get; set; }
        public Nullable<int> Address_Street { get; set; }
        public string Address_House { get; set; }
        public string Address_Number { get; set; }
        public string MinPrice { get; set; }
        public string MaxPrice { get; set; }
        public int AgentId { get; set; }
        public int ClientId { get; set; }
        public string MinArea { get; set; }
        public string MaxArea { get; set; }
        public Nullable<int> MinRooms { get; set; }
        public Nullable<int> MaxRooms { get; set; }
        public Nullable<int> MinFloor { get; set; }
        public Nullable<int> MaxFloor { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Street Street { get; set; }
    }
}
