//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgency.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lands
    {
        public int ID_Land { get; set; }
        public string Address_City { get; set; }
        public Nullable<int> Address_Street { get; set; }
        public string Address_House { get; set; }
        public string Address_Number { get; set; }
        public string Coordinate_latitude { get; set; }
        public string Coordinate_longitude { get; set; }
        public string TotalArea { get; set; }
    
        public virtual Street Street { get; set; }
    }
}
